Update Lab 5 (#21)

diff --git a/lab5/Makefile b/lab5/Makefile
--- a/lab5/Makefile
+++ b/lab5/Makefile
@@ -12,6 +12,10 @@ build: ${C_SRC}
 
 install: build ${PY_SRC}
 	@echo "Installing CBI..."
+	@if ! command -v pip &> /dev/null; then \
+		echo "pip not found, installing..."; \
+		apt-get update && apt-get install -y python3-pip; \
+	fi
 	@python3 -m pip install --use-pep517 --upgrade --editable . 1> /dev/null 2>&1
 	@echo "CBI installed."
 
@@ -31,6 +35,10 @@ clean-instrumentation:
 
 clean-package:
 	@echo "Cleaning cbi..."
+	@if ! command -v pip &> /dev/null; then \
+		echo "pip not found, installing..."; \
+		apt-get update && apt-get install -y python3-pip; \
+	fi
 	@python3 -m pip uninstall --yes cbi 2> /dev/null
 	@rm -f /usr/local/bin/cbi
 	@rm -rf */__pycache__ *.egg-info
